site_name: Learning Graphs
site_description: 'A microsite for teaching how to create and maintain learning graphs (concept dependency graphs) for education.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/learning-graphs/'
repo_url: 'https://github.com/dmccreary/learning-graphs'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md
  - Chapters:
    - Table of Contents: chapters/index.md
    - Learning Graphs: chapters/01-learning-graphs.md
    - Bloom's Taxonomy: chapters/02-blooms-taxonomy.md
    - Rhizomatic Learning: chapters/02-rhizomatic-learning.md
    - Concepts: chapters/02-concepts.md
    - Concept Dependency: chapters/03-concept-dependency.md
    - Concept Taxonomies: chapters/04-concept-taxonomies.md
    - Displaying Graphs: chapters/05-displaying-graphs.md
    - Vis.js: chapters/06-vis-js.md
    - Dependency Analysis: chapters/15-dependency-analysis.md
    - Customizing Lesson Plans: chapters/16-customizing-lesson-plans.md
    - LMS Integration: chapters/17-lms-integration.md
    - Building Intelligent Agents: chapters/18-agents.md
    - Validating Learning Graphs: chapters/19-validating.md

  - Concepts:
    - Introduction: concepts/index.md
    - concepts/50-concepts.md
    - concepts/taxonomy.md
  
  - Case Studies:
    - Introduction: case-studies/index.md
    # - Low-Latency: case-studies/low-latency.md
    - Agents: case-studies/agents.md
    - Beginning Electronics: case-studies/beginning-electronics.md
    - Circuits: case-studies/circuits.md
    - Clocks ans Watches: case-studies/clocks-and-watches.md
    - Data Science: case-studies/data-science.md
    - Geometry: case-studies/geometry.md
    - Graph Algorithms: case-studies/graph-algorithms.md
    - Intelligent Textbooks: case-studies/intelligent-textbooks.md
    - Learning Graph: sims/graph-viewer/index.md
    - MicroPython: case-studies/micropython.md
    - MicroSims: case-studies/microsims.md
    - Personal Finance: case-studies/personal-finance.md
    - Python: case-studies/python.md
    - Signal Processing: case-studies/signal-processing.md
    - Spectrum Analyzer: case-studies/spectrum-analyzer.md
    - STEM Robots: case-studies/stem-robots.md
    - Systems Thinking: case-studies/systems-thinking.md

  - Vis.js Tutorial:
    - Intro: vis/index.md
    - Lab 1 - Default Behavior: vis/lab-01.md
    - Lab 2 - JSON: vis/lab-02.md
    - Lab 3 - Node Properties:  vis/lab-03.md
    - Lab 4 - Edge Properties: vis/lab-04.md
    - Lab 5 - Custom Shapes: vis/lab-05.md
    - Physics Parameters: vis/physics-params/index.md
    - Fix X Positions: vis/fix-x-positions/index.md            
    - Dependency Graph: vis/concept-dependency-graph.md
    - Trace: vis/trace/index.md
    - CSV Reader: vis/csv-reader/index.md
    - Learn Python Example: vis/learn-python/index.md
    - Legends: vis/legends/index.md
    - Legend Checkboxes: vis/legend-checkboxes/index.md
    - Hover Text: vis/hover-text/index.md
    - Double Click: vis/double-click/index.md
    - Open URL: vis/open-url/index.md
    - Groups: vis/groups/index.md
    - Clusters: vis/clusters/index.md
    - Templates: vis/templates/index.md
    - Node Enricher: vis/node-enricher/index.md
    - Network Properties: vis/network-properties/index.md
    - Search: vis/search/index.md
    - Graph Viewer: vis/graph-viewer/index.md
    - Comblined Viewer: vis/combined-viewer/index.md
    - Graph Editor: vis/graph-editor/index.md
    - Edit Nodes: vis/edit-nodes/index.md
  
  - Sample Prompts:
    - Introduction: prompts/index.md
    - Course Description: prompts/01-course-description.md
    - Concept Enumeration: prompts/02-concept-enumeration.md
    - Concept Dependencies: prompts/03-concept-dependencies.md
    - Concept Taxonomies: prompts/04-taxonomies.md
    - Concept Classifier: prompts/20-degree-histogram.md
    - Concept Viewer: prompts/05-concept-viewer.md
    - Concept Editor: prompts/10-vis-editor.md
    - Word Cloud: prompts/11-word-cloud.md
    - Degree Histogram: prompts/20-degree-histogram.md
    - Concept Classifier: prompts/04b-classifier.md
    - Graph Editor: prompts/30-graph-editor.md
    - Creating Skill: prompts/40-create-skill.md
    - Quiz: prompts/06-quiz.md
  
  - MicroSims:
    - Intro: sims/index.md
    - Learning Graph: sims/learning-graph/index.md
    - Book Generation Workflow: sims/book-gen-workflow/index.md
    - Concept to Content Viewer: sims/concept-to-content-viewer/index.md
    - Bloom's Taxonomy: sims/blooms-taxonomy/index.md
    - MicroSim Template: sims/template/index.md
  
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Checklist: checklist.md
  - License: license.md
  - Student Volunteers Wanted: student-volunteers-wanted.md
  - Contact: contact.md
 
# Dan's MicroSite Standards from here down

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'orange'
    accent: 'blue'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - markdown.extensions.extra
  - pymdownx.superfences
extra_css:
  - css/extra.css
extra:
  analytics:
    provider: google
     # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-Z6JDD2PWQZ