site_name: Learning Graphs
site_description: 'A microsite for teaching how to create and maintain learning graphs (concept dependency graphs) for education.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/learning-graphs/'
repo_url: 'https://github.com/dmccreary/learning-graphs'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md
  - Chapters:
    - Table of Contents: chapters/index.md
    - Learning Graphs: chapters/01-learning-graphs.md
    - Concepts: chapters/02-concepts.md
    - Concept Dependency: chapters/03-concept-dependency.md
    - Concept Taxonomies: chapters/04-concept-taxonomies.md
    - Displaying Graphs: chapters/05-displaying-graphs.md
    - Vis.js: chapters/06-vis-js.md
    - Enumerating Concepts: chapters/10-enumerating-concepts.md
    - Generating Dependencies: chapters/11-generating-dependencies.md
    - Generating Taxonomies: chapters/12-generating-taxonomies.md
    - Dependency Analysis: chapters/15-dependency-analysis.md
    - Customizing Lesson Plans: chapters/16-customizing-lesson-plans.md
    - LMS Integration: chapters/17-lms-integration.md
    - Building Intelligent Agents: chapters/18-agents.md
  - Case Studies:
    - Low-Latency: case-studies/low-latency.md
  - Vis:
    - Intro: vis/index.md
    - Graph Viewer: vis/graph-viewer/index.md
    - Editor: vis/graph-editor/index.md

  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Checklist: checklist.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX